version: "3.9"
services:
  jabs:
    build:
      context: .
      args:
        user: appuser
        group: appuser
        uid: 225893
        gid: 513
    volumes:
      - type: bind
        source: ./src/
        target: /app/src/
        read_only: true
      - type: bind
        source: ./output/
        target: /app/output/
    command: /bin/sh -c "
      mvn package &&
      su appuser -c 'cd /app/ && java -jar ./target/jabs.jar'
      "
